### ISSUE TITLE
Add other examples

### ISSUE THREAD

**Issue by kinow** [elliotfontaine/awesome-cylc#3]
Hi! I used to keep a YouTube playlist with videos related to Cylc (will search for that), and also some bookmarks. I'll search for that later, but I searched some that I remembered. Maybe some of these would be interesting for this list?

- eWaterCycle (interesting that they have CWL and Cylc, although I think it was Cylc executing CWL workflows): https://blog.esciencecenter.nl/fairifying-ewatercycle-8a61cf93b81c?gi=e0614a00fb4f & https://github.com/eWaterCycle/ewatercycle-forecast
- Commercial solution with Cylc & PBS by Altair - https://www.altair.com.es/newsroom/articles/cylc-altairs-pbs-professional-power-weather-modeling-at-australias-bureau-of-meteorology/
- Some model optimisation with Cylc https://gmd.copernicus.org/articles/11/2153/2018/

And found this one now while searching for the ewatercycle (couldn't recall the name of the project, only that it was dutch and hydrology-related): https://www.waternz.org.nz/Article?Action=View&Article_id=2699

**Comment by kinow** [comment]
Ha! Found the playlist. I haven't updated it in a while, so there might be more interesting material out there :+1: 

https://www.youtube.com/playlist?list=PLxlfTM52ynRZZ7rtLkoKANWiIFn92d6je

**Comment by hjoliver** [comment]
More about Altair's PBS + Cylc "Weather Solution": 
- https://altair.com/weather-climate
- https://web.altair.com/en/cylc-weather-solution
